### ISSUE TITLE
Fix schedule

### ISSUE THREAD

**Issue by nuest** [o2r-project/agile-2017#1]
The conference organizers advise to put deadlines rather "too early", because of the high number of accepted proposals and Wageningen's hotels being potentially filled quickly. With this in mind I created a timeline draft:

- submission deadline: **March 19**
- assignment of reviewers: March 21
- reviews due: April 2
  - confirmed reviewers for this period
    - @schibalski
    - @JudithVerstegen
    - @vwmaus 
    - @ploewe
    - @mrtnhmtz 
    - @foost 
    - @edzer 
- notification of acceptance: **April 4**
- agenda published: April 10
- workshop: **May 9**
- publication of report: May 31

@edzer @MarkusKonk I am on holidays until March 21. If you'd be available to assign the submissions to the reviewers, then we can also push that date to a couple of weeks earlier.

Alternatively, we could go way earlier and put the deadline to Feb 12 and assign reviewers on Feb 13/14.

**Comment by foost** [comment]
I don't think that an earlier deadline is necessary. btw, I am available as reviewer during the review period.

**Comment by crstn** [comment]
The missing schedule on the website is a bit confusing, when are you planning to add it?

**Comment by nuest** [comment]
Tomorrow morning we will have a telco with @foost and then publish the schedule.
