### ISSUE TITLE
AGILE2018-Tiinas-new-issue

### ISSUE THREAD

**Issue by tiinasarjakoski** [o2r-project/agile-2017#10]
tefiurtegduy

**Comment by nuest** [comment]
@tiinasarjakoski Can you complete the information requested, please?

**Comment by nuest** [comment]
Also, if you find the time, please don't forget to take a look at the preprint on your trip to Lund, see https://doi.org/10.7287/peerj.preprints.26561v1 (all code and material was updated by now and is available at https://github.com/nuest/reproducible-research-and-giscience)
