### ISSUE TITLE
Jeremy Azzopardi

### ISSUE THREAD

**Issue by jer-azz** [o2r-project/agile-2017#11]
1. preferred hands-on session:
 **Python**

2. a short description of experience in R and/or Python:

**Experience in using python as a tool for data management (mostly automating repetitive tasks) as well as some experience as part of my master's degree (using python to process some results). Example: Iterating through hundreds of data packages, finding all relevant shapefiles and access databases, converting to OGC GML and csv and renaming + repackaging relevant folders, etc. some experience in relevant packages such as numpy, use of spyder for geodata , etc **

3. a summary of computational work, if available with references to published papers, data or code, and
plans for future computer-based research:
**None really, my plan is to take some courses in data analytics which would eventually help towards a  phd. My interest in this workshop is partly due to my job as datasamordnare at the Swedish National Data Service**

**Comment by nuest** [comment]
@jer-azz Thanks for your registration! Please don't forget to read the preprint at https://doi.org/10.7287/peerj.preprints.26561v1 (all code and material was updated by now and is available at https://github.com/nuest/reproducible-research-and-giscience)
