### ISSUE TITLE
AGILE - Francisco Ramos

### ISSUE THREAD

**Issue by francisuji** [o2r-project/agile-2017#12]
1. preferred hands-on session (R or Python),
R

2. a short description of experience in R and/or Python

Basic statements and R for leaflet

3. a summary of computational work, if available with references to published papers, data or code

Computer Scientist with programming skills, I have coded in Java, Javascript, Swift, C++, etc.
http://franciscoramos.name

4. plans for future computer-based research.

Data and Statistics Analysis with R and GPU Programming

**Comment by nuest** [comment]
Thanks for your registration! Please don't forget to take a look at the preprint on your trip to Lund at https://doi.org/10.7287/peerj.preprints.26561v1 (all code and material was updated by now and is available at https://github.com/nuest/reproducible-research-and-giscience)
