### ISSUE TITLE
registration for Agile workshop - Stefan Steiniger

### ISSUE THREAD

**Issue by mentaer** [o2r-project/agile-2017#13]
1  - preferred hands-on session (R or Python):
=> Python
2 - a short description of experience in R and/or Python
=> I did a bit scripting in Python with Yupiter and QGIS; not much though
3  - a summary of computational work, if available with references to published papers, data or code,
=> My main work has been around java-GIS programming mostly with/for OpenJUMP. However, I haven't touched any code now since 2 years. See:
- Steiniger et al. (2008) on urban pattern recognition based on building structures : a wee bit old now and original work was done in Matlab and Jump in 2006: https://onlinelibrary.wiley.com/doi/full/10.1111/j.1467-9671.2008.01085.x 
- Steiniger and Hunter (2013) - an animal movement analysis toolbox programmed in 2009-10
https://onlinelibrary.wiley.com/doi/full/10.1002/wsb.168
- Poorazizi et al. (2015): a social media analysis platform written by a doctoral student (I didn't code anything): 
http://www.mdpi.com/2220-9964/4/3/1389/html
- and lately we have worked on a set of urban sustainability indicators in R, but here as well I also did not write a line of code on this. A manuscript has been submitted to Cities and code is here: https://github.com/CEDEUS/city-indicators-calculation-scripts

4  - plans for future computer-based research.
=> Currently I mainly working with my team on an urban accessibility/ analysis platform see Steiniger et al. 2013 (https://www.sciencedirect.com/science/article/pii/S2214140517308691) and on urban sustainability indicators.

**Comment by mentaer** [comment]
btw. Just watching without really doing hands-on is also fine for me; because as I say: I haven't touched code since 2 years. But certainly would be fun to see if I can get our indicators to run/analyse in Python instead of R.

**Comment by nuest** [comment]
Thanks for your registration! The workshop should be an excellent excuse for your to _finally_ touch some code again!

Please don't forget to take a look at the preprint on your trip to Lund at https://doi.org/10.7287/peerj.preprints.26561v1 (all code and material was updated by now and is available at https://github.com/nuest/reproducible-research-and-giscience)
