### ISSUE TITLE
AGILE Workshop Registration - Stefan Wiemann

### ISSUE THREAD

**Issue by swiemann** [o2r-project/agile-2017#14]
- preferred hands-on session (R or Python)
	- R
	
- a short description of experience in R and/or Python
	- R: statistical analysis in projects in the field of statistical air quality modeling and the analysis of hydro-meteorological extreme events; combination with OpenCPU platform for service-based R processing
	- Python: primary use as scripting language in combination with ArcGIS or FME
	
- a summary of computational work, if available with references to published papers, data or code
	- experienced with Java, Web languages (HTML, JavaScript, PHP), R, Python
	- current GitHub repositories (also referenced in a number of articles):
		- https://github.com/GeoinformationSystems/xtruso_R (EXTRUSO R package)
		- https://github.com/GeoinformationSystems/xtruso_web (EXTRUSO information portal)
		- https://github.com/GeoinformationSystems/SpatialDataFusion (PhD work)

- plans for future computer-based research
	- mainly application-based programming in projects
	- further development of PhD work on spatial data fusion

**Comment by nuest** [comment]
Thanks for your registration! You might be unchallenged as a developer, but you always learn something from reproducing other people's work.

Please don't forget to take a look at the preprint on your trip to Lund at https://doi.org/10.7287/peerj.preprints.26561v1 (all code and material was updated by now and is available at https://github.com/nuest/reproducible-research-and-giscience)
