### ISSUE TITLE
Registration Lars Harrie, Lund

### ISSUE THREAD

**Issue by LarsHarrie** [o2r-project/agile-2017#15]
1) Prefer Python
2) Do only some Python coding myself, but I supervise PostDocs and PhD students that do much coding.  In some projects we use the Jupyter environment for sharing code with the future aim to make the code writing more transparent.
3) A project where part of the code is in Python available on Github is published in:
https://www.tandfonline.com/doi/full/10.1080/13658816.2018.1441416
Another article that deals with data integration is found in:
https://www.tandfonline.com/doi/pdf/10.1080/10095020.2015.1071065
At the Agile conference I will present a short paper that describes how we deal with part of the computations in ICOS CP (https://www.icos-cp.eu/) that utilizes Python Jupyter notebook. 
4) Is interested to learn and improve structuring of code and annotate data for improving the transparency in the studies made by our group in Lund.

**Comment by nuest** [comment]
Thanks for your registration!

_Do you think your papers would be available for a reproduction attempt?_

Please don't forget to take a look at the preprint on your trip to Lund at https://doi.org/10.7287/peerj.preprints.26561v1 (all code and material was updated by now and is available at https://github.com/nuest/reproducible-research-and-giscience)
