### ISSUE TITLE
AGILE Workshop Registration - Simon Oulevay

### ISSUE THREAD

**Issue by AlphaHydrae** [o2r-project/agile-2017#16]
Apologies for submitting my registration after the due date. I did not know I was coming to AGILE for sure until today.

1. **Preferred hands-on session (R or Python)**
  Python
1. **A short description of experience in R and/or Python**
  I have some Python scripting experience but am not proficient. However, I am a programmer and know several other dynamic languages (JavaScript, Ruby), and will brush up on my skills with a few tutorials before the workshop.
1. **A summary of computational work, if available with references to published papers, data or code**
  No computational/scientific work to speak of. I am a programmer mostly working with JavaScript, Java, Ruby, HTML, CSS.
1. **Plans for future computer-based research**
  Nothing specific right now, but my institute is working in the area of GIS and machine learning where the learned skills will surely prove useful.

(I am a bit of an intruder in that I am a mostly a web programmer with little to no experience in computational work or scientific publications. However, I have an interest in GIS, literate programming, specifically Jupyter notebooks, and reproducibility. Hence why I would like to participate in the workshop if you have any room left.)

**Comment by nuest** [comment]
Thanks for your registration!

_Your registration date is later than the newest list of participants we have_, so just to make sure: **you did register with the conference organisers, too?**

It will be great to have your "developer perspective" on things supplementing the researcher perspective of other participants.

Please don't forget to take a look at the preprint on your trip to Lund if you have time, see https://doi.org/10.7287/peerj.preprints.26561v1 (all code and material was updated by now and is available at https://github.com/nuest/reproducible-research-and-giscience)

**Comment by AlphaHydrae** [comment]
Yes, I did register on May 28th and paid the fee today, so I might not be on any lists yet. Thank you for the materials. I'll be sure to take a look.
