### ISSUE TITLE
Review process

### ISSUE THREAD

**Issue by nuest** [o2r-project/agile-2017#2]
@MarkusKonk @edzer Feedback welcome!

## Draft for review process

This workshop runs a public peer review. The review process described here is therefore transparent for submitters and tries to be both brief and explicit.

1. Submitters create a pull request (PR) with their submission. By creating the PR the submitter accepts that their work will be published under a Creative Commons Attribution 4.0 International License.
1. The organization committee (@o2r-project/agile-2017-org-committee) checks the form of the submission and assigns the PR to at least one member of @o2r-project/agile-2017-reviewers to conduct the main review following the [guidelines](https://github.com/o2r-project/agile-2017/wiki/Guidelines-for-reviewers). Reviewers are welcome to follow new PRs and volunteer for a submission.
1. After the review is completed, the reviewer creates a the _review recommendation comment_ on the PR mentioning the organizing committee (`@o2r-project/agile-2017-org-committee`) and including one of the following statements: _Review recommendation: Accept for presentation_, _Review recommendation: Accept for presentation after revision_,  _Review recommendation: Reject_
1. All reviewers are welcome to give a short comment on a submission.
1. In case of _Accept for presentation after revision_, the PR is kept open until the recommendation is updated to either _Accept for presentation_, or _Reject_.
1. Once the review recommendations for all submissions are either acceptance or rejection, the @o2r-project/agile-2017-org-committee holds a meeting [public Gitter chat](https://gitter.im/o2r-project/agile-2017) and discusses all recommendation considering the overall programme and bounding conditions (numbers of possible slots, diversity of topics). The committee then make a _decision comment_ for each submission, trying to follow the reviewers' recommendation: _Decision: Accept for presentation_, _Decision: Reject_
1. The _decision comment_ invites all review committee members (`@o2r-project/agile-2017-reviewers`) to briefly check the review arguments and cast a vote using _"thumb up/down"_ [reactions on the comment](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments). There must be a simple majority and the review committee is the tie breaker.
1. In case of acceptance of the submission, the PR is merged by @o2r-project/agile-2017-org-committee. In case of rejection, the pull request is closed without merge (a list of accepted and rejected submissions will be included in the [workshop report](#4).

**Comment by MarkusKonk** [comment]
Hier meine Kommentare:

- "[...] that her work will be published"
- heißt Punkt 3, dass #3 nicht mehr aktuell ist? Das widerspricht sich momentan etwas
- ab Punkt 5 bin ich etwas verwirrt. Wird in Punkt 7 über die Reviewer recommendation entschieden oder über organization commitee discussion? Müssen sich alle Reviewer durch alle Submissions klicken und voten oder wird das auch zugeorndet?

**Comment by nuest** [comment]
@MarkusKonk What exactly are the contradictions between 3. and #3 ?

Tried to clarify the language regarding the other comments.

**Comment by foost** [comment]
Suggest to rephrase
5. "In case of _Accept for presentation after revision_, the PR is kept open until the recommendation is updated to either _Accept for presentation_, or _Reject_."
6. "Once the review recommendations ...."

Step 7 seems a bit complicated - is it really necessary to describe it in that much detail now?

**Comment by MarkusKonk** [comment]
No difference between them, just a missing #.

**Comment by nuest** [comment]
I simplified Step 7 a bit and made the changes suggested in https://github.com/o2r-project/agile-2017/issues/2#issuecomment-271833344

**Comment by nuest** [comment]
Moved to wiki https://github.com/o2r-project/agile-2017/wiki/Review-process
